framework:
    cache:
        pools:
            redis_cache:
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis.connection'
                default_lifetime: 3600
